image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: poetry install # runs during prebuild
    command: echo 'poetry install finished'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
