name: Docker

on:
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/angrymeir/secscanner2junit
          tags: |
            type=semver,pattern={{version}}

      - name: Sleep for 180 seconds # so that the package has been published to PyPI in the meantime
        run: sleep 180
        shell: bash

      - name: Kaniko build
        uses: aevea/action-kaniko@v0.9.0
        with:
          image: ${{ env.REGISTRY }}/angrymeir/secscanner2junit
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          tag_with_latest: true
          extra_args: --build-arg=version=${{ github.ref_name }}
